#!/usr/bin/env bash
# setup.sh — generated by repo-configurator wizard
# Target repository: RhetorKit/docs-test
#
# PREREQUISITES:
#   gh auth status  (must show authenticated session with 'repo' scope)
#   gh --version    (v2.8+ for label import support)
#
# USAGE:
#   Copy the output files to your target repository, then run:
#   bash setup.sh
#
# Review each section before running. Commands are grouped and safe to re-run
# (most gh commands are idempotent or will fail gracefully if already applied).

set -euo pipefail

REPO="RhetorKit/docs-test"
BRANCH="main"

echo "==> Configuring RhetorKit/docs-test ..."
echo ""

# ── Repository Settings ───────────────────────────────────────────────────────

echo "==> Applying repository-level settings ..."

gh repo edit "$REPO" \
  --enable-squash-merge \
  --enable-merge-commit=false \
  --enable-rebase-merge=false \
  --delete-branch-on-merge

echo "  Merge strategy: squash_only"
echo "  Auto-delete head branches: enabled"


# ── Labels ────────────────────────────────────────────────────────────────────

echo ""
echo "==> Importing labels from .github/labels.yml ..."
gh label import .github/labels.yml --repo "$REPO"
echo "  Labels imported."

# ── Branch Protection ─────────────────────────────────────────────────────────

echo ""
echo "==> Applying branch protection rules to $BRANCH ..."

gh api \
  --method PUT \
  "/repos/$REPO/branches/$BRANCH/protection" \
  --input - <<'PROTECTION_EOF'
{
  "required_status_checks": {
    "strict": false,
    "contexts": ["link-check", "spellcheck"]
  },
  "enforce_admins": false,
  "required_pull_request_reviews": {
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": true,
    "required_approving_review_count": 1,
    "require_last_push_approval": false
  },
  "restrictions": null,
  "required_conversation_resolution": true,
  "allow_force_pushes": false,
  "allow_deletions": false
}
PROTECTION_EOF

echo "  Branch protection applied:"
echo "    Review gate: strict_gate"
echo "    Conversation resolution required: true"
echo "    Branches up to date required: false"
echo "    Force pushes: disabled"
echo "    Deletions: disabled"

# High-risk paths use Repository Rulesets (path-aware, requires 2 approvals)
echo ""
echo "==> Creating high-risk docs ruleset ..."

gh api \
  --method POST \
  "/repos/$REPO/rulesets" \
  --input - <<'RULESET_EOF'
{
  "name": "high-risk-docs-protection",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/main"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 2,
        "dismiss_stale_reviews_on_push": true,
        "require_code_owner_review": true,
        "require_last_push_approval": false,
        "required_review_thread_resolution": true
      }
    },
    { "type": "deletion" },
    { "type": "non_fast_forward" }
  ]
}
RULESET_EOF

echo "  High-risk ruleset created (2 approvals + CODEOWNER required)."

# ── Workflows ─────────────────────────────────────────────────────────────────

echo ""
echo "==> Enabling workflows ..."
gh workflow enable docs_triage.yml --repo "$REPO" 2>/dev/null || echo "  (docs_triage.yml not yet pushed — enable after first commit)"
gh workflow enable docs_stale_pr.yml --repo "$REPO" 2>/dev/null || echo "  (docs_stale_pr.yml not yet pushed — enable after first commit)"

# ── Verification ──────────────────────────────────────────────────────────────

echo ""
echo "==> Verifying configuration ..."

gh api "repos/$REPO" \
  --jq '{squash: .allow_squash_merge, merge: .allow_merge_commit, rebase: .allow_rebase_merge, auto_merge: .allow_auto_merge, delete_branch: .delete_branch_on_merge}'

gh api "/repos/$REPO/branches/$BRANCH/protection" \
  --jq '{required_approvals: .required_pull_request_reviews.required_approving_review_count, dismiss_stale: .required_pull_request_reviews.dismiss_stale_reviews, codeowner_required: .required_pull_request_reviews.require_code_owner_reviews, conversation_resolution: .required_conversation_resolution.enabled, force_push: .allow_force_pushes.enabled}'

echo ""
echo "==> Labels present:"
gh label list --repo "$REPO" --json name --jq '.[].name' | sort

echo ""
echo "==> Setup complete for $REPO"
echo ""
echo "NEXT STEPS:"
echo "  1. Copy all output files to your target repository"
echo "  2. Replace any remaining [PLACEHOLDER] tokens"
echo "  3. Push to $BRANCH and verify workflows trigger on a test PR"
echo "  5. Review SETUP_SUMMARY.md with your team before announcing the governance framework"
