#!/usr/bin/env bash
# setup.sh — generated by repo-configurator wizard
# Target repository: RhetorKit/docs-test
#
# PREREQUISITES:
#   gh auth status  (must show authenticated session with 'repo' scope)
#   gh --version    (v2.8+ for label import support)
#
# USAGE:
#   Copy the output files to your target repository, then run:
#   bash setup.sh
#
# Review each section before running. Commands are grouped and safe to re-run
# (most gh commands are idempotent or will fail gracefully if already applied).
